version: '3.3'
services:
 mysql:
  container_name: mysql
  image: mysql:8.0.19
  restart: always
  command:
   - --character-set-server=utf8mb4
   - --collation-server=utf8mb4_general_ci
   - --default-time_zone=+8:00
  environment:
   TZ: Asis/Shanghai
   MYSQL_ROOT_PASSWORD: felixwc
  ports:
   - "3306:3306"
  volumes:
   - ./data/mysql:/var/lib/mysql
