version: "3.1"
services:
  nginx:
    image: daocloud.io/library/nginx:1.13.2
    container_name: nginx-stand-alone
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./data:/local/nginx
networks:
  default:
    external: true
    name: mynet