version: '3'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/data/logs
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=test123
        volumes:
            - ./data:/data/db
            - ./logs:/data/logs
        ports:
            - 27017:27017
networks:
  default:
    external: true
    name: mynet
