version: "3.1"
services:
  zk1:
    image: daocloud.io/library/zookeeper:3.6.1
    restart: always
    container_name: zk1
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181  server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
  zk2:
    image: daocloud.io/library/zookeeper:3.6.1
    restart: always
    container_name: zk2
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181  server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
  zk3:
    image: daocloud.io/library/zookeeper:3.6.1
    restart: always
    container_name: zk3
    ports:
      - 2184:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181  server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
